<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="User-PC" name="Teacher.ValidateAssignmentLevelCOAttainment" tests="3" failures="3" timestamp="16 May 2017 09:28:53 GMT" time="2731.971" errors="0">
  <testcase name="exicute" time="912.471" classname="Teacher.ValidateAssignmentLevelCOAttainment">
    <failure type="java.lang.AssertionError" message="Incorrect CO attainment for &#039;AutoCO3&#039;, &#039;44&#039;in assignmentLab - SetOptionalDiffCOExpected=&#039;AutoCO3&#039;, &#039;44&#039;">
      <![CDATA[java.lang.AssertionError: Incorrect CO attainment for 'AutoCO3', '44'in assignmentLab - SetOptionalDiffCOExpected='AutoCO3', '44'
	at org.testng.Assert.fail(Assert.java:94)
	at Teacher.ValidateAssignmentLevelCOAttainment.exicute(ValidateAssignmentLevelCOAttainment.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:970)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- exicute -->
  <testcase name="exicute" time="906.590" classname="Teacher.ValidateAssignmentLevelCOAttainment">
    <failure type="java.lang.AssertionError" message="Incorrect CO attainment for &#039;AutoCO3&#039;, &#039;44&#039;in assignmentLab - SetOptionalDiffCOExpected=&#039;AutoCO3&#039;, &#039;44&#039;">
      <![CDATA[java.lang.AssertionError: Incorrect CO attainment for 'AutoCO3', '44'in assignmentLab - SetOptionalDiffCOExpected='AutoCO3', '44'
	at org.testng.Assert.fail(Assert.java:94)
	at Teacher.ValidateAssignmentLevelCOAttainment.exicute(ValidateAssignmentLevelCOAttainment.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:970)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- exicute -->
  <testcase name="exicute" time="912.910" classname="Teacher.ValidateAssignmentLevelCOAttainment">
    <failure type="java.lang.AssertionError" message="Incorrect CO attainment for &#039;AutoCO3&#039;, &#039;44&#039;in assignmentLab - SetOptionalDiffCOExpected=&#039;AutoCO3&#039;, &#039;44&#039;">
      <![CDATA[java.lang.AssertionError: Incorrect CO attainment for 'AutoCO3', '44'in assignmentLab - SetOptionalDiffCOExpected='AutoCO3', '44'
	at org.testng.Assert.fail(Assert.java:94)
	at Teacher.ValidateAssignmentLevelCOAttainment.exicute(ValidateAssignmentLevelCOAttainment.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- exicute -->
</testsuite> <!-- Teacher.ValidateAssignmentLevelCOAttainment -->
