<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="User-PC" name="Teacher.CreateCO" tests="9" failures="3" timestamp="9 Mar 2017 06:12:57 GMT" time="853.091" errors="0">
  <testcase name="createCO" time="33.408" classname="Teacher.CreateCO">
    <failure type="java.lang.AssertionError" message="Not able to click on Update CO">
      <![CDATA[java.lang.AssertionError: Not able to click on Update CO
	at org.testng.Assert.fail(Assert.java:94)
	at Teacher.CreateCO.createCO(CreateCO.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- createCO -->
  <testcase name="createCO" time="33.215" classname="Teacher.CreateCO">
    <failure type="java.lang.AssertionError" message="Not able to click on Update CO">
      <![CDATA[java.lang.AssertionError: Not able to click on Update CO
	at org.testng.Assert.fail(Assert.java:94)
	at Teacher.CreateCO.createCO(CreateCO.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:970)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- createCO -->
  <testcase name="createCO" time="129.587" classname="Teacher.CreateCO"/>
  <testcase name="createCO" time="129.885" classname="Teacher.CreateCO"/>
  <testcase name="createCO" time="105.356" classname="Teacher.CreateCO"/>
  <testcase name="createCO" time="129.325" classname="Teacher.CreateCO"/>
  <testcase name="createCO" time="33.239" classname="Teacher.CreateCO">
    <failure type="java.lang.AssertionError" message="Not able to click on Update CO">
      <![CDATA[java.lang.AssertionError: Not able to click on Update CO
	at org.testng.Assert.fail(Assert.java:94)
	at Teacher.CreateCO.createCO(CreateCO.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:970)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- createCO -->
  <testcase name="createCO" time="129.568" classname="Teacher.CreateCO"/>
  <testcase name="createCO" time="129.508" classname="Teacher.CreateCO"/>
</testsuite> <!-- Teacher.CreateCO -->
