<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="User-PC" name="Validate Marks and CO attainment" tests="1" failures="1" timestamp="3 May 2017 04:39:48 GMT" time="15.58" errors="0">
  <testcase name="exicute" time="15.567" classname="Teacher.ValidateAssignmentLevelCOAttainment">
    <failure type="java.lang.AssertionError" message="Login Failed for:maym@inpods.com expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Failed for:maym@inpods.com expected [true] but found [false]
	at Common.Login.LoginD(Login.java:34)
	at Teacher.ValidateAssignmentLevelCOAttainment.ReadAssignmentLevelCOattainmentValidationData(ValidateAssignmentLevelCOAttainment.java:71)
	at Teacher.ValidateAssignmentLevelCOAttainment.exicute(ValidateAssignmentLevelCOAttainment.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- exicute -->
</testsuite> <!-- Validate Marks and CO attainment -->
