<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INPOD" name="API Validation" tests="1" failures="1" timestamp="9 Jun 2016 11:25:34 GMT" time="363.629" errors="0">
  <testcase name="CallLogIn" time="363.601" classname="StudentAPI.APILogIn">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at StudentAPI.APILogIn.CallLogIn(APILogIn.java:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- CallLogIn -->
</testsuite> <!-- API Validation -->
