<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="User-PC" name="Create PO" tests="1" failures="1" timestamp="8 May 2017 08:42:23 GMT" time="50.744" errors="0">
  <testcase name="createCO" time="50.742" classname="Tech.CreatePO">
    <failure type="java.lang.AssertionError" message="Not able to click on Update PO">
      <![CDATA[java.lang.AssertionError: Not able to click on Update PO
	at Tech.CreatePO.createCO(CreatePO.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- createCO -->
</testsuite> <!-- Create PO -->
