<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="User-PC" name="lesson_Creation_Upload_txt" tests="1" failures="1" timestamp="11 Jan 2017 10:01:36 GMT" time="1544.084" errors="0">
  <testcase name="CreateLesson" time="1544.082" classname="Teacher.Lesson">
    <failure type="java.lang.AssertionError" message="Not able to create the lesson Upload_txt">
      <![CDATA[java.lang.AssertionError: Not able to create the lesson Upload_txt
	at Teacher.Lesson.CreateLesson(Lesson.java:142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- CreateLesson -->
</testsuite> <!-- lesson_Creation_Upload_txt -->
