<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="User-PC" name="lesson_lesson_chapter" tests="1" failures="1" timestamp="1 Mar 2017 12:59:44 GMT" time="28.717" errors="0">
  <testcase name="CreateLesson" time="28.708" classname="Teacher.Lesson">
    <failure type="java.lang.AssertionError" message="Not able to create the lesson lessonDemoChapter">
      <![CDATA[java.lang.AssertionError: Not able to create the lesson lessonDemoChapter
	at Teacher.Lesson.CreateLesson(Lesson.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- CreateLesson -->
</testsuite> <!-- lesson_lesson_chapter -->
